name: CI Build and Unit Test

on:
  push:
    branches: [ "main" ] # Only run on pushes to the main branch
  # pull_request: # Removed pull_request trigger
  #   branches: [ "**" ]

jobs:
  build-and-unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Or your project's specific Node version

      - name: Setup PNPM
        uses: pnpm/action-setup@v4

      - name: Clean Turbo Cache
        run: rm -rf node_modules/.cache/turbo

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run Linters
        run: pnpm lint

      - name: Build packages
        run: pnpm build

      - name: Run Unit Tests Only
        # Excludes files ending with integration.test.ts
        run: pnpm test -- --testPathIgnorePatterns='integration\\.test\\.ts$' 